### PR TITLE
Add ColonyUpgraded event and handler

### PR DESCRIPTION
**Pull request by alicjakujawa**
This PR adds in ColonyUpgraded event definition and handler 

Contributes to DEV-141

### CODE REVIEW

**Comment by rdig** [comment]
Note that this won't work properly until I merge #2347 (which pulls in the new colonyNetwork changes and builds a new version of `colonyJS`)

**Comment by alicjakujawa** [comment]
> Note that this won't work properly until I merge #2347 (which pulls in the new colonyNetwork changes and builds a new version of `colonyJS`)

No worry, its either way on hold, as its need a bit of network work before

**Comment by rdig** [comment]
This is now unblocked and can be worked on

**Review by area — APPROVED** [review]

**Review by chinins — APPROVED** [review]
all good

**Pull request merged**
